# Generated by Django 4.0.6 on 2022-07-30 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(max_length=11, verbose_name='Номер телефона')),
                ('operator', models.CharField(choices=[('mts', 'МТС'), ('megafon', 'Мегафон'), ('rosstelecom', 'Росстелеком'), ('beeline', 'Билайн'), ('tele2', 'Теле2'), ('yota', 'Йота')], max_length=11, verbose_name='Мобильный оператор')),
                ('tag', models.CharField(max_length=30, verbose_name='Произвольная метка')),
                ('timezone', models.CharField(choices=[('UTC−12:00', 'UTC−12:00'), ('UTC−11:00', 'UTC−11:00'), ('UTC−10:00', 'UTC−10:00'), ('UTC−9:30', 'UTC−9:30'), ('UTC−9:00', 'UTC−9:00'), ('UTC−8:00', 'UTC−8:00'), ('UTC−7:00', 'UTC−7:00'), ('UTC−6:00', 'UTC−6:00'), ('UTC−5:00', 'UTC−5:00'), ('UTC−4:00', 'UTC−4:00'), ('UTC−3:30', 'UTC−3:30'), ('UTC−3:00', 'UTC−3:00'), ('UTC−2:00', 'UTC−2:00'), ('UTC−1:00', 'UTC−1:00'), ('UTC−0:00', 'UTC−0:00'), ('UTC+1:00', 'UTC+1:00'), ('UTC+2:00', 'UTC+2:00'), ('UTC+2:00', 'UTC+2:00'), ('UTC+3:30', 'UTC+3:30'), ('UTC+4:00', 'UTC+4:00'), ('UTC+4:30', 'UTC+4:30'), ('UTC+5:00', 'UTC+5:00'), ('UTC+5:30', 'UTC+5:30'), ('UTC+5:45', 'UTC+5:45'), ('UTC+6:00', 'UTC+6:00'), ('UTC+6:30', 'UTC+6:30'), ('UTC+7:00', 'UTC+7:00'), ('UTC+8:00', 'UTC+8:00'), ('UTC+8:45', 'UTC+8:45'), ('UTC+9:00', 'UTC+9:00'), ('UTC+9:30', 'UTC+9:30'), ('UTC+10:00', 'UTC+10:00'), ('UTC+10:30', 'UTC+10:30'), ('UTC+11:00', 'UTC+11:00'), ('UTC+12:00', 'UTC+12:00'), ('UTC+12:45', 'UTC+12:45'), ('UTC+13:00', 'UTC+13:00'), ('UTC+14:00', 'UTC+14:00')], max_length=9, verbose_name='Часовой пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('filter', models.CharField(max_length=20, verbose_name='Фильтр')),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UTC−12:00', 'UTC−12:00'), ('UTC−11:00', 'UTC−11:00'), ('UTC−10:00', 'UTC−10:00'), ('UTC−9:30', 'UTC−9:30'), ('UTC−9:00', 'UTC−9:00'), ('UTC−8:00', 'UTC−8:00'), ('UTC−7:00', 'UTC−7:00'), ('UTC−6:00', 'UTC−6:00'), ('UTC−5:00', 'UTC−5:00'), ('UTC−4:00', 'UTC−4:00'), ('UTC−3:30', 'UTC−3:30'), ('UTC−3:00', 'UTC−3:00'), ('UTC−2:00', 'UTC−2:00'), ('UTC−1:00', 'UTC−1:00'), ('UTC−0:00', 'UTC−0:00'), ('UTC+1:00', 'UTC+1:00'), ('UTC+2:00', 'UTC+2:00'), ('UTC+2:00', 'UTC+2:00'), ('UTC+3:30', 'UTC+3:30'), ('UTC+4:00', 'UTC+4:00'), ('UTC+4:30', 'UTC+4:30'), ('UTC+5:00', 'UTC+5:00'), ('UTC+5:30', 'UTC+5:30'), ('UTC+5:45', 'UTC+5:45'), ('UTC+6:00', 'UTC+6:00'), ('UTC+6:30', 'UTC+6:30'), ('UTC+7:00', 'UTC+7:00'), ('UTC+8:00', 'UTC+8:00'), ('UTC+8:45', 'UTC+8:45'), ('UTC+9:00', 'UTC+9:00'), ('UTC+9:30', 'UTC+9:30'), ('UTC+10:00', 'UTC+10:00'), ('UTC+10:30', 'UTC+10:30'), ('UTC+11:00', 'UTC+11:00'), ('UTC+12:00', 'UTC+12:00'), ('UTC+12:45', 'UTC+12:45'), ('UTC+13:00', 'UTC+13:00'), ('UTC+14:00', 'UTC+14:00')], default='begin', max_length=10, verbose_name='Статус отправки')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='backend.client', verbose_name='ID клиента')),
                ('newsletter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='backend.newsletter', verbose_name='ID рассылки')),
            ],
        ),
    ]
